### PR TITLE
Add yolov11

### PR DESCRIPTION
**Pull request by JohnnyHopp**
[Yolov11](https://github.com/ultralytics/ultralytics) is implemented, which is exported with opset=17. #1569 

The default model is yolo11x, which can be loaded by ailia and run properly.

However, all other models 11n, 11s, 11m and 11l have some issues when loaded by ailia, the error prints as below. I tried to run with onnxruntime, there's no problem. A little bit weird...

```
 INFO arg_utils.py (13) : Start!
 INFO arg_utils.py (163) : env_id: 1
 INFO arg_utils.py (166) : CPU-IntelMKL
 INFO model_utils.py (89) : ONNX file and Prototxt file are prepared!
Traceback (most recent call last):
  File "/mnt/d/ax/ailia-models/object_detection/yolov11/yolov11.py", line 376, in <module>
    main()
 INFO model_utils.py (89) : ONNX file and Prototxt file are prepared!
Traceback (most recent call last):
  File "/mnt/d/ax/ailia-models/object_detection/yolov11/yolov11.py", line 376, in <module>
    main()
Traceback (most recent call last):
  File "/mnt/d/ax/ailia-models/object_detection/yolov11/yolov11.py", line 376, in <module>
    main()
  File "/mnt/d/ax/ailia-models/object_detection/yolov11/yolov11.py", line 360, in main
    main()
  File "/mnt/d/ax/ailia-models/object_detection/yolov11/yolov11.py", line 360, in main
  File "/mnt/d/ax/ailia-models/object_detection/yolov11/yolov11.py", line 360, in main
    net = ailia.Net(MODEL_PATH, WEIGHT_PATH, env_id=args.env_id)
  File "/home/jun/miniconda3/lib/python3.10/site-packages/ailia/wrapper.py", line 266, in __init__
    self._open_stream(stream)
  File "/home/jun/miniconda3/lib/python3.10/site-packages/ailia/wrapper.py", line 302, in _open_stream
    core.check_error(code, self.__net)
  File "/home/jun/miniconda3/lib/python3.10/site-packages/ailia/core.py", line 931, in check_error
    raise e(detail)
ailia.core.AiliaBrokenDataException: code: -4 (The specified file was broken.)
+ error detail : unexpected escape sequence:S
```

### CODE REVIEW

**Comment by kyakuno** [comment]
モデルアップロード済み
https://storage.googleapis.com/ailia-models/yolov11/yolov11l.onnx

**Comment by kyakuno** [comment]
ailia SDK 1.5だと推論できた。

```
kyakuno@mbakk yolov11 % python3 yolov11.py 
 INFO arg_utils.py (13) : Start!
 INFO arg_utils.py (163) : env_id: 2
 INFO arg_utils.py (166) : MPSDNN-Apple M2
 INFO model_utils.py (74) : Downloading onnx file... (save path: yolov11x.onnx)
 INFO model_utils.py (80) : ======================= 100.00% ( 222606KB )]

 INFO model_utils.py (82) : Downloading prototxt file... (save path: yolov11x.onnx.prototxt)
 INFO model_utils.py (88) : ======================= 100.00% ( 305KB )]

 INFO model_utils.py (89) : ONNX file and Prototxt file are prepared!
 INFO license.py (81) : ailiaへようこそ。ailia SDKは商用ライブラリです。特定の条件下では、無償使用いただけますが、原則として有償ソフトウェアです。詳細は https://ailia.ai/license/ を参照してください。
 INFO yolov11.py (263) : input.jpg
 INFO yolov11.py (270) : Start inference...
object_count=23
+ idx=0
  category=[ person ]
  prob=0.91845703125
  x=0.7640625
  y=0.6384976525821596
  w=0.134375
  h=0.3615023474178404
+ idx=1
  category=[ car ]
  prob=0.91748046875
  x=0.0
  y=0.6549295774647887
  w=0.1859375
  h=0.1596244131455399
+ idx=2
  category=[ person ]
  prob=0.888671875
  x=0.615625
  y=0.6572769953051644
  w=0.0703125
  h=0.323943661971831
+ idx=3
  category=[ person ]
  prob=0.88037109375
  x=0.890625
  y=0.6807511737089202
  w=0.0625
  h=0.2934272300469484
+ idx=4
  category=[ person ]
  prob=0.875
  x=0.6609375
  y=0.704225352112676
  w=0.0890625
  h=0.29577464788732394
+ idx=5
  category=[ person ]
  prob=0.873046875
  x=0.259375
  y=0.6924882629107981
  w=0.0640625
  h=0.26291079812206575
+ idx=6
  category=[ handbag ]
  prob=0.83984375
  x=0.7640625
  y=0.8990610328638498
  w=0.0328125
  h=0.10093896713615023
+ idx=7
  category=[ car ]
  prob=0.78564453125
  x=0.0
  y=0.7276995305164319
  w=0.028125
  h=0.11502347417840375
+ idx=8
  category=[ backpack ]
  prob=0.77099609375
  x=0.7890625
  y=0.7065727699530516
  w=0.08125
  h=0.17370892018779344
+ idx=9
  category=[ backpack ]
  prob=0.7294921875
  x=0.6234375
  y=0.6995305164319249
  w=0.04375
  h=0.11502347417840375
+ idx=10
  category=[ bicycle ]
  prob=0.6748046875
  x=0.246875
  y=0.795774647887324
  w=0.0625
  h=0.19248826291079812
+ idx=11
  category=[ person ]
  prob=0.64501953125
  x=0.259375
  y=0.6572769953051644
  w=0.01875
  h=0.07981220657276995
+ idx=12
  category=[ person ]
  prob=0.640625
  x=0.2140625
  y=0.6572769953051644
  w=0.0171875
  h=0.09154929577464789
+ idx=13
  category=[ traffic light ]
  prob=0.564453125
  x=0.4984375
  y=0.5845070422535211
  w=0.0109375
  h=0.051643192488262914
+ idx=14
  category=[ person ]
  prob=0.56201171875
  x=0.1734375
  y=0.647887323943662
  w=0.0265625
  h=0.09624413145539906
+ idx=15
  category=[ traffic light ]
  prob=0.4443359375
  x=0.33125
  y=0.5774647887323944
  w=0.015625
  h=0.0539906103286385
+ idx=16
  category=[ person ]
  prob=0.42919921875
  x=0.4296875
  y=0.6596244131455399
  w=0.015625
  h=0.06103286384976526
+ idx=17
  category=[ person ]
  prob=0.421142578125
  x=0.203125
  y=0.647887323943662
  w=0.0171875
  h=0.09154929577464789
+ idx=18
  category=[ person ]
  prob=0.376708984375
  x=0.7125
  y=0.6666666666666666
  w=0.0265625
  h=0.09859154929577464
+ idx=19
  category=[ traffic light ]
  prob=0.376220703125
  x=0.5125
  y=0.5892018779342723
  w=0.009375
  h=0.04225352112676056
+ idx=20
  category=[ person ]
  prob=0.36083984375
  x=0.2984375
  y=0.6596244131455399
  w=0.0171875
  h=0.0539906103286385
+ idx=21
  category=[ person ]
  prob=0.268310546875
  x=0.459375
  y=0.6455399061032864
  w=0.0125
  h=0.03051643192488263
+ idx=22
  category=[ traffic light ]
  prob=0.267333984375
  x=0.428125
  y=0.6056338028169014
  w=0.009375
  h=0.023474178403755867
 INFO yolov11.py (290) : saved at : output.png
 INFO yolov11.py (299) : Script finished successfully.
kyakuno@mbakk yolov11 % 
```

**Comment by kyakuno** [comment]
ailia SDK 1.2.13ではエラーで、1.2.14では通る。

**Comment by kyakuno** [comment]
@JohnnyHopp What ailia version did you use?

**Comment by JohnnyHopp** [comment]
> @JohnnyHopp What ailia version did you use?

I'm using ailia 1.5.0, the default command using model type v11x is fine. The issue occurs with other model types, "v11n", "v11s" , "v11m" and "v11l". Can you have a try with the command below?

`python3 yolov11.py --model_type v11n`

**Comment by kyakuno** [comment]
@JohnnyHopp Understood! Thanks.

**Comment by kyakuno** [comment]
@JohnnyHopp Main issue is prototxt is broken. So I will reconstruct prototxt.

**Review by kyakuno — APPROVED** [review]

**Pull request merged**
