### PR TITLE
added HIFI GAN model (tacotron2)

### PR DESCRIPTION
**Pull request by YToleubay**
Added -m hifi option in tacotron2.py to choose HIFI GAN model Updated read.me
Updated requirements.txt
Added license file for HIFI GAN

### CODE REVIEW

**Comment by kyakuno** [comment]
@YToleubay Please set
  REMOTE_PATH_HIFH = "https://storage.googleapis.com/ailia-models/hifigan/"
and directly download from
https://storage.googleapis.com/ailia-models/hifigan/generator_dynamic.onnx
https://storage.googleapis.com/ailia-models/hifigan/generator_dynamic.onnx.prototxt

**Comment by YToleubay** [comment]
> TODO : hifi-ganを日本語に適用した場合の音質を確認

[https://drive.google.com/drive/folders/1xnZh097otr5pqjFUqspI6dAfwknSz02X?usp=drive_link](url) is a link to audio samples. You can compare HIFI gan and tsukuyomi models outputs.

**Comment by kyakuno** [comment]
@YToleubay 
Thank you for the analysis data. It seems like we can't use for japanese.

**Comment by kyakuno** [comment]
@YToleubay 
Which model did you export to ONNX? LJ_V3?
https://github.com/jik876/hifi-gan

**Comment by YToleubay** [comment]
> @YToleubay Which model did you export to ONNX? LJ_V3? https://github.com/jik876/hifi-gan

I have exported LJ_FT_T2_V1. I checked the paper, it was the model that provided highest scores

**Review by kyakuno — APPROVED** [review]

**Pull request merged**
